# Generated by Django 4.1.3 on 2024-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding"),
                    ("party", "Party"),
                    ("club", "Club Event"),
                    ("government", "Government Event"),
                    ("conference", "Conference"),
                    ("concert", "Concert"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
